name: sport_coach
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  smooth_page_indicator: ^1.1.0
  auto_route: ^8.1.3
  auto_route_generator: ^8.0.0
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  freezed: ^2.5.2
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.10
  json_serializable: ^6.8.0

flutter:

  uses-material-design: true

  assets:
    - assets/logo/
    - assets/images/
    - assets/icons/

  fonts:
   - family: SF Pro
     fonts:
       - asset: assets/fonts/SFPRODISPLAYREGULAR.OTF
